app_name/views.py
from flask import (
    Blueprint, flash, redirect, render_template, request, session, url_for
)
from . import db
from .models import Movie
from .forms import AddMovieForm, UpdateMovieForm, SearchMovieForm
from . import api
from flask_login import login_required, current_user
import requests

bp = Blueprint('views', __name__)


@bp.route('/')
def home():
    response = requests.get(url=api.TOP_RATED_MOVIE, params={
        'api_key': api.API_KEY,
    })
    data = response.json()['results'][0:9]
    all_movies = Movie.query.order_by(Movie.rating.desc()).limit(3).all()
    db.session.commit()
    return render_template('index.html', movies=all_movies, recommended=data, user=current_user)


@bp.route('/library')
@login_required
def library():
    all_movies = db.session.query(Movie).all()
    return render_template('library.html', movies=all_movies, user=current_user)


@bp.route('/search', methods=['GET', 'POST'])
@login_required
def search_movie():
    form = SearchMovieForm()
    if form.validate_on_submit():
        movie_title = form.title.data
        response = requests.get(url=api.SEARCH_MOVIE_URL, params={
            'api_key': api.API_KEY,
            'query': movie_title
        })
        data = response.json()['results']
        return render_template('select.html', movies=data)
    return render_template('search.html', form=form)


@bp.route('/add', methods=['GET', 'POST'])
def add_movie():
    movie_id = request.args.get('id')
    movie_url = f'{api.ID_URL}/{movie_id}'
    response = requests.get(url=movie_url, params={
        'api_key': api.API_KEY,
    })
    data = response.json()
    form = AddMovieForm()
    if form.validate_on_submit():
        movie_to_add = Movie(title=data['original_title'], year=data['release_date'][0:3], description=data['overview'],
                             rating=form.rating.data, review=form.review.data,
                             img_url=f"https://image.tmdb.org/t/p/w500/{data['poster_path']}", user_id=current_user.id)
        db.session.add(movie_to_add)
        db.session.commit()
        return redirect(url_for('views.library'))
    return render_template('add.html', movie=data, form=form)

@bp.route('/edit', methods=['GET', 'POST'])
def edit_movie():
    form = UpdateMovieForm()
    movie_id = request.args.get('id')
    movie = Movie.query.get(movie_id)
    if form.validate_on_submit():
        movie.rating = float(form.data.get('rating'))
        movie.review = form.data.get('review')
        db.session.commit()
        return redirect(url_for('views.library'))
    return render_template('edit.html', movie=movie, form=form)

@bp.route('/delete')
def delete_movie():
    movie_id = request.args.get('id')
    movie_to_delete = Movie.query.get(movie_id)
    db.session.delete(movie_to_delete)
    db.session.commit()
    return redirect(url_for('views.library'))

@bp.route('/<title>', methods=['GET', 'POST'])
def get_movie_details(title):
    movie_id = request.args.get('id')
    movie_url = f'{api.ID_URL}/{movie_id}'
    response = requests.get(url=movie_url, params={
        'api_key': api.API_KEY,
    })
    data = response.json()
    return render_template('movie_details.html', movie=data)

app_name/templates/add.html
<!-- Inherit from the base.html-->
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
<!-- Change the title of the page -->
{% block title %}Register{% endblock %}
<!-- Add in the main content -->
{% block content %}
<h1 class="display-3 text-center text-white my-3">{{movie.title}}</h1>
  <div class="container">
    <div class="form-control bg-black w-50 row mx-auto">
      <div class="col-lg-8 col-md-10 mx-auto text-white my-3">
       {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "dark"}) }}
      </div>
    </div>
  </div>
{% endblock %}

app_name/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!--   FONTAWESOME IMPORT  -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="stylesheet"
          type="text/css">

    <!--   BOOTSTRAP IMPORT  -->
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
            crossorigin="anonymous"
    />
    <!--  STYLES.CSS IMPORT  -->
    <link
            rel="stylesheet"
            href="{{ url_for('static', filename='style.css') }}"
    />

    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
<!--  Creating the global navbar  -->
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container-fluid mx-3">
        <a class="navbar-brand" href="/"><i class="d-inline-block fa fa-film align-text-center me-1" style="font-size:18px;"></i>Movie Library</a>
        <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if not current_user.is_authenticated: %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/login">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/register">Register</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="/library">My Library</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/search">Search</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logout">Log out</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Defining the Flash functionality -->
<div class="container-fluid">
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>{{message}}</strong>
        <button
                type="button"
                class="btn-close"
                data-bs-dismiss="alert"
                aria-label="Close"
        ></button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{message}}</strong>
        <button
                type="button"
                class="btn-close"
                data-bs-dismiss="alert"
                aria-label="Close"
        ></button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
</div>
<!--  Start of the main content  -->
{% block content %} {% endblock %}

<!-- BOOTSTRAP IMPORT -->
<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"
></script>
</body>
</html>

app_name/templates/edit.html
<!-- Inherit from the base.html-->
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
<!-- Change the title of the page -->
{% block title %}Edit Movie Review{% endblock %}
<!-- Add in the main content -->
{% block content %}
<h1 class="display-1 text-center text-white">Search for a Movie</h1>
  <div class="container">
    <div class="form-control bg-black w-50 row mx-auto">
      <div class="col-lg-8 col-md-10 mx-auto text-white mt-3">
       {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "dark"}) }}
      </div>
    </div>
  </div>
{% endblock %}

app_name/templates/index.html
<!-- Inherit from the base.html-->
{% extends "base.html" %}
<!-- Change the title of the page -->
{% block title %}Home{% endblock %}
<!-- Add in the main content -->
{% block content %} {% if user.is_authenticated %}
<h1 class="display-5 text-center text-white">
  Hi {{user.username}}, here are some of the highest rated movies.
</h1>
{% else %}
<h1 class="display-5 text-center text-white">
  Here are some of the highest rated movies.
</h1>
{% endif %}

<div
  id="carouselExampleControls"
  class="carousel slide"
  data-bs-ride="carousel"
>
  <div class="carousel-inner">
    {% for movie in movies %}
    <div class="carousel-item active">
        <img
          src="{{movie.img_url}}"
          class="img-fluid d-block mx-auto"
          alt="{{movie.title}} movie image"
        />
    </div>
    {% endfor %}
  </div>
  <button
    class="carousel-control-prev"
    type="button"
    data-bs-target="#carouselExampleControls"
    data-bs-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button
    class="carousel-control-next"
    type="button"
    data-bs-target="#carouselExampleControls"
    data-bs-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class="container mt-5 me-auto">
  <h5 class="text-white">Recommended Movies:</h5>
  <ul class="list-group list-group-flush mb-5 rounded">
    {% for movie in recommended %}
    <a
      href="{{ url_for('views.get_movie_details', title=movie['original_title'], id=movie['id']) }}"
      class="list-group-item text-center"
    >
      {{movie['original_title']}}
    </a>
    {% endfor %}
  </ul>
</div>
{% endblock %}

app_name/templates/library.html
<!-- Inherit from the base.html-->
{% extends "base.html" %} {% import "bootstrap/wtf.html" as wtf %}
<!-- Change the title of the page -->
{% block title %}My Library{% endblock %}
<!-- Add in the main content -->
{% block content %}
<h1 class="display-3 text-center text-white">Welcome to your Movie Reviews!</h1>
<div class="container w-100">
  <div class="row row-cols-12">
    {% for movie in movies: %} {% if movie.user_id == user.id: %}
    <div class="col g-3">
      <div class="card me-auto" style="width: 15rem;">
        <img
          src="{{movie.img_url}}"
          class="card-img-top"
          alt="{{movie.title}} movie image"
        />
        <div class="card-body">
          <h5 class="card-title">{{movie.title}}</h5>
          <p class="card-text"><strong>Rating: </strong> {{movie.rating}}</p>
          <p class="card-text"><strong>Review: </strong>{{movie.review}}</p>
          <a href="{{url_for('views.edit_movie', id=movie.id)}}" class="button"
            ><i class="fas fa-edit mx-2" style="font-size: 18px;"></i
          ></a>
          <a
            href="{{url_for('views.delete_movie', id=movie.id)}}"
            class="button delete-button"
            ><i class="fa fa-trash mx-2" style="font-size: 18px"></i
          ></a>
        </div>
      </div>
    </div>
    {% endif %} {% endfor %}
  </div>
</div>
{% endblock %}

app_name/templates/login.html
<!-- Inherit from the base.html-->
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
<!-- Change the title of the page -->
{% block title %}Register{% endblock %}
<!-- Add in the main content -->
{% block content %}
<h1 class="display-3 text-center text-white my-3">Login</h1>
  <div class="container">
    <div class="form-control bg-black w-50 row mx-auto">
      <div class="col-lg-8 col-md-10 mx-auto text-white my-3">
       {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "dark"}) }}
      </div>
    </div>
  </div>
{% endblock %}

app_name/templates/movie_details.html
<!-- Inherit from the base.html-->
{% extends "base.html" %}
<!-- Change the title of the page -->
{% block title %}Home{% endblock %}
<!-- Add in the main content -->
{% block content %}
<div class="card mb-3 mx-auto" style="max-width:540px;">
  <img src="https://image.tmdb.org/t/p/w500/{{movie['poster_path']}}" class="card-img-top" alt="{{movie.title}} movie image">
  <div class="card-body">
    <h5 class="card-title">{{movie['original_title']}}</h5>
    <p class="card-text">{{movie['overview']}}</p>
    <a href="{{url_for('views.add_movie', id=movie['id'])}}" class="btn btn-dark">Add Movie</a>
  </div>
</div>
{% endblock %}

app_name/templates/register.html
<!-- Inherit from the base.html-->
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
<!-- Change the title of the page -->
{% block title %}Register{% endblock %}
<!-- Add in the main content -->
{% block content %}
<h1 class="display-3 text-center text-white my-3">Register</h1>
  <div class="container">
    <div class="form-control bg-black w-50 row mx-auto">
      <div class="col-lg-8 col-md-10 mx-auto text-white my-3">
       {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "dark"}) }}
      </div>
    </div>
  </div>
{% endblock %}

app_name/templates/search.html
<!-- Inherit from the base.html-->
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
<!-- Change the title of the page -->
{% block title %}Search for a Movie{% endblock %}
<!-- Add in the main content -->
{% block content %}
<h1 class="display-3 text-center text-white">Search for a Movie</h1>
  <div class="container">
    <div class="form-control bg-black w-50 row mx-auto">
      <div class="col-lg-8 col-md-10 mx-auto text-white mt-3">
       {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "dark"}) }}
      </div>
    </div>
  </div>
{% endblock %}

app_name/templates/select.html
<!-- Inherit from the base.html-->
{% extends "base.html" %} {% import "bootstrap/wtf.html" as wtf %}
<!-- Change the title of the page -->
{% block title %}Select Movie{% endblock %}
<!-- Add in the main content -->
{% block content %}
<div class="container">
  {% for movie in movies: %}
  <div class="card mb-3" style="max-width: 540px">
    <a href="{{url_for('views.add_movie', id=movie['id'])}}">
      <div class="row g-0">
        <div class="col-md-4">
          <img
            src="https://image.tmdb.org/t/p/w500/{{movie['poster_path']}}"
            class="img-thumbnail rounded-start"
            alt="{{movie.title}} movie image"
          />
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">{{movie['original_title']}}</h5>
            <p class="card-text">{{movie['overview']}}</p>
          </div>
        </div>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}